### PR TITLE
Converted Modifier's & overload to method

### PR DESCRIPTION
**Pull request by Rartrin**
Converted Modifier's `&` overload to `CombineWith` method.

Also cleaned up the `Equals` method.

### CODE REVIEW

**Review by Chicken-Bones — CHANGES_REQUESTED** [review]
*`CombinedWith` to make it clear it's not in place.

**Comment by Rartrin** [comment]
> *`CombinedWith` to make it clear it's not in place.

"Combined" is past tense though.
I could make the method `readonly`.

Otherwise I can just make a static `Combine` method instead. Actually, that will probably work out the best when it comes time to add in crit and knockback, because then the methods will be `CombineDamages`, `CombineCrits`, `CombineKnockbacks`.

**Comment by Chicken-Bones** [comment]
I believe the convention is to use past tense, as in "the result when this is combined with that" or at least, it clarifies.

I'm also happy with `Modifier.Combine(m1, m2)` but it can't be chained as easily. (unlike the `&` syntax).

`CritModifier` and `KnockbackModifier` should be separate classes if they have separate combine calculations. They shouldn't be assignable to each other. That's a type error.

**Comment by Chicken-Bones** [comment]
Completed in the `StatModifier` PR

**Pull request closed without merging**
