### PR TITLE
1.4

### PR DESCRIPTION
**Pull request by idkman2021**
i got a new idea so i think they should port tmodloader to 1.4 because it adds new features  like list of monsters and new teleporters and would be kinda cool to have them for calamit mod

### CODE REVIEW

**Comment by Mirsario** [comment]
I do not even.

**Comment by NotLe0n** [comment]
Lets gooo

**Comment by Steviegt6** [comment]
I can relate.

**Comment by OliHeamon** [comment]
He did small amounts of :trollface:

**Comment by Steviegt6** [comment]
:trollface:

**Pull request closed without merging**
