### PR TITLE
Actually fix ExampleShield (best practice)

### PR DESCRIPTION
**Pull request by Chicken-Bones**
### What are the changes to ExampleMod?
The dash accessory was implemented by enumerating the player's accessory slots. This approach is contrary to the vanilla and tML design where accessories enable capabilities on the player, and prevents all accessory related hooks or custom slots from working with it.

The new design also puts the movement code in the `PreUpdateMovement` hook, consistent with other movement affecting code.

Overall operation should be easier to understand. Posting here for feedback/thoughts.

### CODE REVIEW

**Review by Itorius — APPROVED** [review]
Looks fine to me

**Review by Mirsario — APPROVED** [review]
This is definitely better, but 1 class per file please.

**Comment by Chicken-Bones** [comment]
> This is definitely better, but 1 class per file please.

What's our ExampleMod policy? should multi-class examples go in a separate namespace/folder?

**Comment by Mirsario** [comment]
> What's our ExampleMod policy? should multi-class examples go in a separate namespace/folder?

I would make a namespace if a piece of content requires additional new data classes/structs, but if it's a ModPlayer, I would probably prefer putting it in Common.Players (or was it Common.ModEntities.Players?), separate from the content piece that uses it. The point is, things like items and tiles they place/projectiles they shoot are already separate, even if that tile/projectile is only used by that item.

**Comment by Chicken-Bones** [comment]
Going to deal with the one class per file problem later.

**Pull request merged**
