### PR TITLE
Update Terraria.Localization.Content.de-DE.tModLoader.json

### PR DESCRIPTION
**Pull request by xTeare**
Added missing translations, fixed some typos

### Description of the Change

There where some typos and missing translations, which i fixed or added

### Why this should be merged into tModLoader

Because the German Community might be happy about a correct translation

### Benefits

Better Translation

### CODE REVIEW

**Comment by Jofairden** [comment]
Thx a lot
It might be wise for us to keep this open until we are certain about a release, then we can review if everything got translated.

**Comment by xTeare** [comment]
Yeah, just let me know if something is missing

**Comment by Jofairden** [comment]
Added to 0.11 milestone so we dont forget to merge this

**Comment by Jofairden** [comment]
Thanks again!

**Comment by xTeare** [comment]
You're Welcome.

If you need more Translations, just inform me

**Pull request merged**
