### PR TITLE
Installer: Unix installer written in bash

### PR DESCRIPTION
**Pull request by Kreyren**
Draft issue: Not finished.

This issue improves provided scripts in tModLoader, fixes spellcheck and adds alternative to `tModLoader.Installer.jar` so that end-user doesn't have to use java (which seems insane to prioritize java over bash on linux).

TODO: Force GUI since steam doesn't output text output.
TODO: Test on darwin
TODO: Provide installer

### CODE REVIEW

**Comment by Jofairden** [comment]
Hey, thanks for starting on this and keep us updated! May I recommend renaming the project to "installer-bash". We will/should rename installer2 to "installer-java".  (Feel free to do that in this PR so that those are updated when it merges)

**Comment by Kreyren** [comment]
> Hey, thanks for starting on this and keep us updated! May I recommend renaming the project to "installer-bash". We will/should rename installer2 to "installer-java". (Feel free to do that in this PR so that those are updated when it merges)

Will do :)

**Comment by Kreyren** [comment]
Relevant: Winetricks is using `zenity` (https://en.wikipedia.org/wiki/Zenity) for the GUI. We might be able to use the same thing assuming that steam doesn't show any dialogs nor output by default.

**Comment by Jofairden** [comment]
I think I will close this due to inactivity, plus installation on Steam (most users) will be automatic.

**Pull request closed without merging**
