### PR TITLE
Added a hook to prevent items from stacking in the world

### PR DESCRIPTION
**Pull request by MrSlimeDude**
### What is the new feature?
This PR adds a hook for ModItem which returns a boolean which allows the modder to allow items to stack in the inventory but not in the world.
There is an issue for this PR: #1106 
### Why should this be part of tModLoader?
Because it will allow mods to create unique in world item interactions based on certain criteria. (See issue)
### Are there alternative designs?
See issue
### Sample usage for the new feature
```C#
using Terraria.ModLoader;

public class ExampleItem : ModItem
{

	...

	public override bool CanStackInWorld(Item item2) {
		return false; //Prevents the item from stacking in the world but still allows it to stack in the inventory 
	}

}

```
### ExampleMod updates

None

### CODE REVIEW

**Comment by Solxanich** [comment]
Good base to the PR. At a glance, my main comment is to rename item1 and item2 parameters to have meaningful names. Its indistinguishable in globalItem and confusing if you aren't familiar with how its setup internally.


Beyond the code, a couple of questions of consideration for the formal reviewer and author alike, can't tell from the issue;
1) Should the ability to force items to stack in world that don't stack in inventory also exist? And if so, how manage conflicts? I only forsee this being used to improve end-user performance,  so I don't think it's needed.
2) Should the stacking check include context sensitivity? IE should we allow specifying only prevent stacking if the player dropped the item AND not if it dropped from other sources?
3) As the outcome raised is merging two in world items in to something different,
A) should this PR include the additional hook/modifications to hooks to facilitate?
B) does tML need to consider how to handle in-world crafting recipe conflicts?

**Review by Chicken-Bones — APPROVED** [review]
The position of this hook means it will only be called for 2 items of the same `type`. Please add this to the documentation for the hooks. 

In response to @Solxanich 's questions
1. I don't see a use case for forced stacking at this stage
2. I don't think additional context is required. This hook covers the current use cases.
3. Merging 2 items for a 'recipe' or 'interaction' would require a different hook, and should be designed in a declarative manner similar to other recipes, where tML chooses the recipe to 'apply' and mods can see which recipes exist.

**Comment by MrSlimeDude** [comment]
@Solxanich  I agree with your naming suggestion but was unable to think of any better names myself so I tried to explain the name in the method documentation. If you are able to think of one I would be happy to rename the parameters in a new commit. Thank you for the feedback.

**Comment by Solxanich** [comment]
The documentation is good and clarifies well enough for me.
I'll drop a line in the discord to let someone know its ready for merge as it looks like all feedback is addressed. 
Thanks for the contribution! If you're interested in contributing more, I'd recommend dropping a line in our discord to have yourself added to the 'collaborators' chat as its a good place to get modular feedback on larger PRs

**Pull request merged**
