### PR TITLE
Made "DefaultToXX" in Item.cs Publicization

### PR DESCRIPTION
**Pull request by Crapsky233**
There are a few "DefaultToXX" methods in Item.cs such as DefaultToBow, DefaultToRangedWeapon etc. But unfortunally, they are private. This PR makes them the public. These may help modders while setting defaults to their items.

### CODE REVIEW

**Comment by Mirsario** [comment]
How is CloneDefaults not sufficient?

**Comment by Crapsky233** [comment]
> How is CloneDefaults not sufficient?

When using CloneDefaults, it is usually necessary to reset some of the  stats again to get a different item. The "DefaultTo" method gives different kinds of items a quicker way to set stats. One line of code can meet the requirements, and it can also guide Modders to set stats for an item, it makes their task easier.
Also, "DefaultTo" as an additional method, it can complement with CloneDefaults.

**Comment by JavidPack** [comment]
This makes sense. The DefaultTo stuff is for quickly setting up the required fields for a specific item type.

**Review by Chicken-Bones — APPROVED** [review]
Good alternative to `CloneDefaults` if you don't want to override all the properties of a specific item. I see this as a positive.

**Pull request merged**
