### PR TITLE
Many Examplemod Sprites

### PR DESCRIPTION
**Pull request by Pacnysam**
### What are the changes to ExampleMod?
Many sprites, list below

### Do these changes need additional documentation?
no

### Sprites changed/added:
example ore tile + item
example bed, chair, candle, and table, tiles + items
example chest key
example golf ball
example life fruit
example custom damage accessory
example magic weapon

### UPDATED, new sprites added are listed below
example item
example lamp, dresser, bathtub, lantern, bar, tiles + items
example chest, locked + unlocked

all sprites included use daim's example palette

image

### CODE REVIEW

**Comment by Itorius** [comment]
Do you want to include the furniture sprites in this PR or another one? Otherwise I'm happy to merge it in.

**Comment by Pacnysam** [comment]
> Do you want to include the furniture sprites in this PR or another one? Otherwise I'm happy to merge it in.

this one please, thanks :]

**Comment by Pacnysam** [comment]
updated, added several more sprites

**Comment by Jofairden** [comment]
Nice style, would be cool if we could convert the entire ExampleMod to it.

**Review by Jofairden — APPROVED** [review]

**Comment by Chicken-Bones** [comment]
Is this ready for merge? Ask and we shall deliver. Nice work

**Comment by Pacnysam** [comment]
> Is this ready for merge? Ask and we shall deliver. Nice work

this is ready to merge, thanks :]

**Pull request merged**
