### PR TITLE
Revert "Changed UIManagePublished offline text and changed caps on MBOfflineW…"

### PR DESCRIPTION
**Pull request by sertuslegrand40**
Reverts tModLoader/tModLoader#1001

### CODE REVIEW

**Comment by JavidPack** [comment]
why?

**Comment by GoodPro712** [comment]
what?

**Comment by Mirsario** [comment]
@GoodPro712 Why did the original PR from this guy that this one reverts consist of your commit? I'll just close this, seems like an inadequate scenario.

**Comment by GoodPro712** [comment]
What was the original PR doing

**Pull request closed without merging**
